/// Versioned immutable messages for the native image-processing channel.
///
/// Generated JSON conversion keeps the Flutter/native schema explicit. These
/// values contain paths and numeric edit parameters only; pixel buffers and
/// document metadata are deliberately absent.
library;

import 'package:doc_scanly/core/contracts/geometry/perspective_transform.dart';
import 'package:doc_scanly/core/contracts/image_processing/image_processing.dart';
import 'package:doc_scanly/core/contracts/models/page.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'native_image_processing_dto.freezed.dart';
part 'native_image_processing_dto.g.dart';

/// The currently supported platform-channel message schema.
const nativeImageProcessingSchemaVersion = 1;

/// The currently supported colour-pipeline contract.
const nativeImageProcessingColourPipelineVersion = 1;

/// Serializable homography coefficients in row-major order.
@freezed
abstract class NativeHomographyDto with _$NativeHomographyDto {
  /// Creates a serializable homography.
  const factory NativeHomographyDto({
    required double h00,
    required double h01,
    required double h02,
    required double h10,
    required double h11,
    required double h12,
    required double h20,
    required double h21,
  }) = _NativeHomographyDto;

  /// Deserializes a homography generated by a native response or fixture.
  factory NativeHomographyDto.fromJson(Map<String, dynamic> json) =>
      _$NativeHomographyDtoFromJson(json);

  const NativeHomographyDto._();

  /// Converts [value] into the channel representation.
  ///
  /// Returns an immutable DTO and does not throw for a finite or non-finite
  /// value; request validation rejects non-finite geometry before submission.
  factory NativeHomographyDto.fromDomain(Homography value) =>
      NativeHomographyDto(
        h00: value.h00,
        h01: value.h01,
        h02: value.h02,
        h10: value.h10,
        h11: value.h11,
        h12: value.h12,
        h20: value.h20,
        h21: value.h21,
      );

  /// Converts this DTO into a domain [Homography].
  ///
  /// Returns the coefficient-preserving value. It does not validate finiteness;
  /// [ImageRenderRequest.validate] performs that boundary check.
  Homography toDomain() => Homography(
    h00: h00,
    h01: h01,
    h02: h02,
    h10: h10,
    h11: h11,
    h12: h12,
    h20: h20,
    h21: h21,
  );
}

/// Serializable enhancement values used by both native implementations.
@freezed
abstract class NativeEnhancementSettingsDto
    with _$NativeEnhancementSettingsDto {
  /// Creates serializable enhancement settings.
  const factory NativeEnhancementSettingsDto({
    required EnhancementFilter filter,
    required double brightness,
    required double contrast,
    required double sharpen,
    required bool shadowRemoval,
  }) = _NativeEnhancementSettingsDto;

  /// Deserializes generated enhancement JSON.
  factory NativeEnhancementSettingsDto.fromJson(Map<String, dynamic> json) =>
      _$NativeEnhancementSettingsDtoFromJson(json);

  const NativeEnhancementSettingsDto._();

  /// Converts [value] into the channel representation.
  factory NativeEnhancementSettingsDto.fromDomain(EnhancementSettings value) =>
      NativeEnhancementSettingsDto(
        filter: value.filter,
        brightness: value.brightness,
        contrast: value.contrast,
        sharpen: value.sharpen,
        shadowRemoval: value.shadowRemoval,
      );

  /// Converts this DTO into domain enhancement settings.
  EnhancementSettings toDomain() => EnhancementSettings(
    filter: filter,
    brightness: brightness,
    contrast: contrast,
    sharpen: sharpen,
    shadowRemoval: shadowRemoval,
  );
}

/// The versioned request submitted to native image processing.
@freezed
abstract class NativeImageRenderRequestDto with _$NativeImageRenderRequestDto {
  /// Creates a native render request.
  const factory NativeImageRenderRequestDto({
    required int schemaVersion,
    required String requestId,
    required String sourcePath,
    required String destinationPath,
    required ImageRenderScale scale,
    required NativeEnhancementSettingsDto enhancement,
    required int jpegQuality,
    required int colourPipelineVersion,
    NativeHomographyDto? transform,
    int? outputWidth,
    int? outputHeight,
    int? maximumPreviewDimension,
  }) = _NativeImageRenderRequestDto;

  /// Deserializes generated request JSON.
  factory NativeImageRenderRequestDto.fromJson(Map<String, dynamic> json) =>
      _$NativeImageRenderRequestDtoFromJson(json);

  const NativeImageRenderRequestDto._();

  /// Converts [request] into the current native schema.
  ///
  /// Returns the generated DTO. Throws [ArgumentError] when [request] fails
  /// domain validation, before any platform call is attempted.
  factory NativeImageRenderRequestDto.fromDomain(ImageRenderRequest request) {
    request.validate();
    return NativeImageRenderRequestDto(
      schemaVersion: nativeImageProcessingSchemaVersion,
      requestId: request.requestId,
      sourcePath: request.sourcePath,
      destinationPath: request.destinationPath,
      scale: request.scale,
      enhancement: NativeEnhancementSettingsDto.fromDomain(request.enhancement),
      jpegQuality: request.jpegQuality,
      colourPipelineVersion: request.colourPipelineVersion,
      transform: request.transform == null
          ? null
          : NativeHomographyDto.fromDomain(request.transform!),
      outputWidth: request.outputWidth,
      outputHeight: request.outputHeight,
      maximumPreviewDimension: request.maximumPreviewDimension,
    );
  }

  /// Converts this versioned DTO into a validated domain request.
  ///
  /// Returns [ImageRenderRequest]. Throws [FormatException] for an unsupported
  /// schema or colour-pipeline version and [ArgumentError] for invalid values.
  ImageRenderRequest toDomain() {
    _requireSchema(schemaVersion);
    if (colourPipelineVersion != nativeImageProcessingColourPipelineVersion) {
      throw FormatException(
        'unsupported colour pipeline version: $colourPipelineVersion',
      );
    }
    final request = ImageRenderRequest(
      requestId: requestId,
      sourcePath: sourcePath,
      destinationPath: destinationPath,
      scale: scale,
      enhancement: enhancement.toDomain(),
      jpegQuality: jpegQuality,
      colourPipelineVersion: colourPipelineVersion,
      transform: transform?.toDomain(),
      outputWidth: outputWidth,
      outputHeight: outputHeight,
      maximumPreviewDimension: maximumPreviewDimension,
    );
    return request..validate();
  }
}

/// The versioned capability returned by a native backend.
@freezed
abstract class NativeImageProcessingCapabilityDto
    with _$NativeImageProcessingCapabilityDto {
  /// Creates a native capability response.
  const factory NativeImageProcessingCapabilityDto({
    required int schemaVersion,
    required ImageProcessingBackendKind backend,
    required bool isSupported,
    required int maximumTextureSize,
    required bool supportsTiling,
  }) = _NativeImageProcessingCapabilityDto;

  /// Deserializes generated capability JSON.
  factory NativeImageProcessingCapabilityDto.fromJson(
    Map<String, dynamic> json,
  ) => _$NativeImageProcessingCapabilityDtoFromJson(json);

  const NativeImageProcessingCapabilityDto._();

  /// Converts this response into a validated domain capability.
  ///
  /// Returns [ImageProcessingCapability]. Throws [FormatException] for an
  /// unsupported schema and [ArgumentError] for incoherent limits.
  ImageProcessingCapability toDomain() {
    _requireSchema(schemaVersion);
    final capability = ImageProcessingCapability(
      backend: backend,
      isSupported: isSupported,
      maximumTextureSize: maximumTextureSize,
      supportsTiling: supportsTiling,
    );
    return capability..validate();
  }
}

/// Serializable stage timings returned by native processing.
@freezed
abstract class NativeImageProcessingTimingsDto
    with _$NativeImageProcessingTimingsDto {
  /// Creates serializable timings measured in microseconds.
  const factory NativeImageProcessingTimingsDto({
    required int decodeMicroseconds,
    required int transformMicroseconds,
    required int encodeMicroseconds,
    required int totalMicroseconds,
  }) = _NativeImageProcessingTimingsDto;

  /// Deserializes generated timing JSON.
  factory NativeImageProcessingTimingsDto.fromJson(Map<String, dynamic> json) =>
      _$NativeImageProcessingTimingsDtoFromJson(json);

  const NativeImageProcessingTimingsDto._();

  /// Converts this DTO into validated domain timings.
  ImageProcessingTimings toDomain() {
    final timings = ImageProcessingTimings(
      decodeMicroseconds: decodeMicroseconds,
      transformMicroseconds: transformMicroseconds,
      encodeMicroseconds: encodeMicroseconds,
      totalMicroseconds: totalMicroseconds,
    );
    return timings..validate();
  }
}

/// Serializable successful output returned by native processing.
@freezed
abstract class NativeImageProcessingResultDto
    with _$NativeImageProcessingResultDto {
  /// Creates a native result.
  const factory NativeImageProcessingResultDto({
    required String destinationPath,
    required int sourceWidth,
    required int sourceHeight,
    required int outputWidth,
    required int outputHeight,
    required ImageProcessingBackendKind backend,
    required NativeImageProcessingTimingsDto timings,
  }) = _NativeImageProcessingResultDto;

  /// Deserializes generated result JSON.
  factory NativeImageProcessingResultDto.fromJson(Map<String, dynamic> json) =>
      _$NativeImageProcessingResultDtoFromJson(json);

  const NativeImageProcessingResultDto._();

  /// Converts this DTO into a validated domain result.
  ImageProcessingResult toDomain() {
    final result = ImageProcessingResult(
      destinationPath: destinationPath,
      sourceWidth: sourceWidth,
      sourceHeight: sourceHeight,
      outputWidth: outputWidth,
      outputHeight: outputHeight,
      backend: backend,
      timings: timings.toDomain(),
    );
    return result..validate();
  }
}

/// The versioned success-or-failure envelope returned by native processing.
@freezed
abstract class NativeImageProcessingResponseDto
    with _$NativeImageProcessingResponseDto {
  /// Creates a response containing exactly one of [result] or [failureKind].
  const factory NativeImageProcessingResponseDto({
    required int schemaVersion,
    NativeImageProcessingResultDto? result,
    ImageProcessingFailureKind? failureKind,
    String? debugDetail,
  }) = _NativeImageProcessingResponseDto;

  /// Deserializes generated response JSON.
  factory NativeImageProcessingResponseDto.fromJson(
    Map<String, dynamic> json,
  ) => _$NativeImageProcessingResponseDtoFromJson(json);

  const NativeImageProcessingResponseDto._();

  /// Converts this envelope into a typed backend response.
  ///
  /// Returns success or failure. Throws [FormatException] when the schema is
  /// unsupported or the envelope contains both/neither outcome.
  ImageProcessingBackendResponse toDomain() {
    _requireSchema(schemaVersion);
    final hasResult = result != null;
    final hasFailure = failureKind != null;
    if (hasResult == hasFailure) {
      throw const FormatException(
        'native response must contain exactly one result or failureKind',
      );
    }
    if (result case final value?) {
      return ImageProcessingBackendResponse.success(value.toDomain());
    }
    return ImageProcessingBackendResponse.failure(
      kind: failureKind!,
      debugDetail: debugDetail,
    );
  }
}

void _requireSchema(int actual) {
  if (actual != nativeImageProcessingSchemaVersion) {
    throw FormatException('unsupported image-processing schema: $actual');
  }
}
