# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  private_lane :setup_variables do
    BUILD_NUMBER_PATH = "../../Jenkins/build_number"
    BUILD_VERSION_PATH = "../../Jenkins/build_version"
    GSP_PATH = "app/google-services.json"
    FIREBASE_APP_ID = "1:511064978644:android:adf3492c6648eb0124b741"
    FIREBASE_CLI_TOKEN = ENV["FIREBASE_CLI_TOKEN"]
    GOOGLE_SERVICE_ACCOUNT_JSON_KEY_PATH = ENV["GOOGLE_SERVICE_ACCOUNT_JSON_KEY_PATH"]
    PACKAGE_NAME = "com.bruxkey.docscanly"
    ANDROID_SIGNING_STORE_FILE = ENV["ANDROID_SIGNING_STORE_FILE"]
    ANDROID_SIGNING_STORE_PASSWORD = ENV["ANDROID_SIGNING_STORE_PASSWORD"]
    ANDROID_SIGNING_KEY_ALIAS = ENV["ANDROID_SIGNING_KEY_ALIAS"]
    ANDROID_SIGNING_KEY_PASSWORD = ENV["ANDROID_SIGNING_KEY_PASSWORD"]
  end

  # The before all will make sure to do this step before running the lane
  before_all do
    # setting up the variables in order to be used inside the lanes
    setup_variables
  end

  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to firebase"
  lane :release_firebase do
    firebase_app_distribution(
      app: FIREBASE_APP_ID,
      groups: "QA",
      # Firebase gets the staging APK; the Play Store gets the production AAB.
      # Both are built by the Release Firebase / Release PlayStore stages.
      apk_path: "../build/app/outputs/apk/release/app-release.apk",
      firebase_cli_token: FIREBASE_CLI_TOKEN,
      googleservice_info_plist_path:GSP_PATH,
      service_credentials_file:GOOGLE_SERVICE_ACCOUNT_JSON_KEY_PATH,
      debug: true
    )
    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  lane :update_build_number do
      buildNumber = fetch_build_number.to_i
      buildVersion = fetch_build_version
      increment_version_code(
        gradle_file_path: "app/build.gradle",
        version_code: buildNumber
      )
      increment_version_name(
        gradle_file_path: "app/build.gradle",
        version_name: buildVersion
      )
  end

#   desc "Create App APK"
#   private_lane :build_APK do
#       buildNumber = fetch_build_number.to_i
#       buildVersion = fetch_build_version
#       increment_version_code(
#         gradle_file_path: "app/build.gradle",
#         version_code: buildNumber
#       )
#       increment_version_name(
#         gradle_file_path: "app/build.gradle",
#         version_name: buildVersion
#       )
#       #gradle(task: "clean")
#       gradle(
#        task: 'assemble',
#         build_type: 'firebase',
#         properties: {
#              "android.injected.signing.store.file" => ANDROID_SIGNING_STORE_FILE,
#              "android.injected.signing.store.password" => ANDROID_SIGNING_STORE_PASSWORD,
#              "android.injected.signing.key.alias" => ANDROID_SIGNING_KEY_ALIAS,
#              "android.injected.signing.key.password" => ANDROID_SIGNING_KEY_PASSWORD,
#          }
#        )
#   end

#   desc "Build App AAB"
#   private_lane :build_AAB do
#       buildNumber = fetch_build_number.to_i
#       buildVersion = fetch_build_version
#       increment_version_code(
#         gradle_file_path: "app/build.gradle",
#         version_code: buildNumber
#       )
#       increment_version_name(
#         gradle_file_path: "app/build.gradle",
#         version_name: buildVersion
#       )
#       #       gradle(task: "clean")
#              gradle(
#                task: 'bundle',
#                build_type: 'store',
#                properties: {
#                    "android.injected.signing.store.file" => ANDROID_SIGNING_STORE_FILE,
#                    "android.injected.signing.store.password" => ANDROID_SIGNING_STORE_PASSWORD,
#                    "android.injected.signing.key.alias" => ANDROID_SIGNING_KEY_ALIAS,
#                    "android.injected.signing.key.password" => ANDROID_SIGNING_KEY_PASSWORD,
#                }
#              )
#   end

  desc "Deploy a new version to the Google Play"
  lane :send_to_play_store do
    upload_to_play_store(
        package_name:PACKAGE_NAME,
        track:"alpha",
        json_key:GOOGLE_SERVICE_ACCOUNT_JSON_KEY_PATH,
        aab: "../build/app/outputs/bundle/release/app-release.aab",
        skip_upload_metadata:true,
        skip_upload_changelogs:true,
        skip_upload_images:true,
        skip_upload_screenshots:true,
    )
  end

  private_lane :fetch_build_number do
    sh(
      command: "cat #{BUILD_NUMBER_PATH}"
    )
  end

  private_lane :fetch_build_version do
    sh(
      command: "cat #{BUILD_VERSION_PATH}"
    )
  end
end
